Add `sendPoll` endpoint
go-telegram-bot-api/telegram-bot-api pull request #366
Opened 2020-08-26 17:54 UTC by pavelgnom

For now it does not support quizes and a bunch of options.

2020-08-31 21:05 UTC, tjhorner commented
@pavelgnom tag me when this is ready for review, will take a look :)

2020-09-05 11:02 UTC, pavelgnom commented
@tjhorner can you please take a look?

2020-09-05 11:11 UTC, pavelgnom commented on bot_test.go
> +	if err != nil && !strings.Contains(err.Error(), "poll has already been closed") {
@tjhorner do you have any thoughts how could we get rid of it?

2020-09-05 18:39 UTC, tjhorner requested changes
LGTM, just a name change and question.

2020-09-05 18:39 UTC, tjhorner commented on configs.go
> +	Anonymous             bool
Let's change this to `IsAnonymous` to keep it consistent with the other fields prefixed with `is_` in the API.

2020-09-05 18:39 UTC, tjhorner commented on helpers.go
> +			ReplyToMessageID: 0,
Wouldn't this be `0` by default?

2020-09-06 20:05 UTC, tjhorner approved these changes

2020-09-06 20:06 UTC, tjhorner commented
@Syfaro mind taking one last look?

2020-10-05 06:56 UTC, pavelgnom commented
@Syfaro @tjhorner do we have any estimate on when that could be merged? Thanks.

2021-08-08 23:06 UTC, pavelgnom commented
I've put some minor improvements there and rebased it with the latest master.
@tjhorner @Syfaro can you please review it once again?

2021-11-08 19:53 UTC, Syfaro commented
I'm sorry it took so long to review this, I really do appreciate the contribution. 

However the `sendPoll` method was implemented in the develop branch a while ago, and that just got merged in so this is no longer needed.

2021-11-08 19:53 UTC, closed without merging